// Imported by the server only. Never send this bank to a client component.
import type { Question, Source } from './types';
const law = (article: string, id: string): Source => ({ label: `Code du travail · ${article}`, url: `https://www.legifrance.gouv.fr/codes/article_lc/${id}` });
const prevention: Source = { label: 'INRS · Fondamentaux de la prévention', url: 'https://www.inrs.fr/demarche/fondamentaux-prevention/ce-qu-il-faut-retenir' };
const accident: Source = { label: 'Assurance Maladie · Accident du travail ou de trajet', url: 'https://www.ameli.fr/assure/droits-demarches/maladie-accident-hospitalisation/accident-travail-trajet' };
const mission: Source = { label: 'Assurance Maladie · Accident sur le lieu de travail, sur le trajet ou en mission', url: 'https://www.ameli.fr/entreprise/vos-salaries/accident-travail-trajet/definition' };
const mp: Source = { label: 'Assurance Maladie · Maladie professionnelle', url: 'https://www.ameli.fr/assure/droits-demarches/maladie-accident-hospitalisation/maladie-professionnelle/maladie-professionnelle' };
const penal: Source = { label: 'INRS · La responsabilité pénale de l’employeur', url: 'https://www.inrs.fr/dms/inrs/CataloguePapier/TS/TI-TS833page44/TS833page44.pdf' };
const obligation = law('L. 4121-1', 'LEGIARTI000035640828');
const principles = law('L. 4121-2', 'LEGIARTI000033019913');
const worker = law('L. 4122-1', 'LEGIARTI000006903153');
const withdrawal = law('L. 4131-1', 'LEGIARTI000006903155');
const others = law('L. 4132-1', 'LEGIARTI000006903159');
const obstruction = law('L. 2317-1', 'LEGIARTI000035634273');
export const QUIZ_VERSION = 1;
export const questions: Question[] = [
  { id: 1, theme: 'Les enjeux de la prévention', slides: '10–11', text: 'En prévention, protéger la santé au travail signifie…', choices: ['Éviter uniquement les blessures visibles.', 'Préserver la santé physique et mentale.', 'Intervenir seulement après un arrêt de travail.', 'Veiller uniquement au confort matériel.'], correct: 1, explanation: 'La santé mentale fait partie de la santé au travail, au même titre que la santé physique. La prévention agit aussi avant tout dommage.', sources: [obligation] },
  { id: 2, theme: 'Les enjeux de la prévention', slides: '11, 21', text: 'Après des menaces, une salariée dort mal. Quel enjeu est principalement illustré par cette conséquence ?', choices: ['Économique', 'Juridique', 'Humain', 'Sociétal'], correct: 2, explanation: 'Les troubles du sommeil concernent directement la santé et la qualité de vie de la personne : c’est l’enjeu humain.', sources: [prevention] },
  { id: 3, theme: 'Les enjeux de la prévention', slides: '11', text: 'Des difficultés mal prises en compte dégradent la confiance entre une équipe et son encadrement. Quel enjeu est au premier plan ?', choices: ['Social', 'Économique', 'Sociétal', 'Juridique'], correct: 0, explanation: 'Le social concerne ici les relations de travail, la coopération et la confiance à l’intérieur de la structure. Il se distingue des effets sur les bénéficiaires ou la société.', sources: [] },
  { id: 4, theme: 'Les enjeux de la prévention', slides: '11–15', text: 'Un remplacement mobilise du temps de recrutement et de formation. Quel enjeu est principalement décrit ?', choices: ['Humain', 'Social', 'Juridique', 'Économique'], correct: 3, explanation: 'Le récit insiste sur les moyens et le temps nécessaires pour maintenir l’activité. Il illustre donc l’enjeu économique, sans exclure d’autres conséquences.', sources: [prevention] },
  { id: 5, theme: 'Les enjeux de la prévention', slides: '11', text: 'Une organisation qui protège les salariés permet de maintenir l’accès des familles à un service. Quel enjeu illustre cet accès au service ?', choices: ['Social, car il s’agit nécessairement des relations entre collègues.', 'Sociétal, car le bénéfice dépasse le collectif de travail.', 'Juridique, car tout service constitue une obligation légale.', 'Uniquement économique, car seul le budget compte.'], correct: 1, explanation: 'Le bénéfice pour les familles se situe au-delà de la structure : il est sociétal. La protection des salariés constitue aussi un enjeu humain.', sources: [] },
  { id: 6, theme: 'Les enjeux de la prévention', slides: '11', text: 'Un même accident peut-il concerner plusieurs enjeux de prévention ?', choices: ['Non, il faut toujours lui attribuer un enjeu unique.', 'Oui, mais seulement s’il entraîne un arrêt.', 'Oui, il peut toucher la santé, le collectif, les moyens, les responsabilités et les tiers.', 'Non, ses conséquences sont uniquement humaines.'], correct: 2, explanation: 'Les cinq enjeux sont une grille de lecture. Un seul événement peut produire plusieurs conséquences, à l’intérieur et au-delà de l’organisation.', sources: [] },
  { id: 7, theme: 'Coûts et événements', slides: '12–16', text: 'Quel exemple illustre un coût indirect d’un accident pour l’organisation ?', choices: ['Le temps de réorganisation des équipes et les retards d’activité.', 'Uniquement le montant des soins hospitaliers.', 'Uniquement le remboursement des médicaments.', 'Seulement les indemnités versées par l’Assurance Maladie.'], correct: 0, explanation: 'La désorganisation mobilise des ressources et peut ralentir l’activité. Ces effets font partie des coûts indirects, parfois moins visibles que les dépenses de soins.', sources: [prevention] },
  { id: 8, theme: 'Coûts et événements', slides: '24', text: 'Une charge tombe près d’un salarié sans le toucher. Quelle attitude sert la prévention ?', choices: ['Classer l’événement sans suite puisqu’il n’y a pas de blessure.', 'Attendre qu’un accident identique provoque un arrêt.', 'Chercher d’abord une personne à sanctionner.', 'Analyser ce presque-accident pour éviter sa répétition.'], correct: 3, explanation: 'L’absence de blessure ne supprime pas le danger. Un presque-accident fournit des informations utiles pour agir avant un dommage.', sources: [prevention] },
  { id: 9, theme: 'Accidents et maladies professionnelles', slides: '23, 27', text: 'Un salarié livre des pizzas pour son employeur et se blesse en chutant pendant une livraison. Quelle qualification faut-il envisager ?', choices: ['Un accident de trajet, puisque le salarié circule.', 'Un accident du travail, puisque le déplacement fait partie de sa mission.', 'Un accident privé, puisqu’il est hors des locaux.', 'Aucune, sauf si l’employeur reconnaît une faute.'], correct: 1, explanation: 'Un déplacement effectué pour réaliser une mission relève du travail. Il ne se confond pas avec le trajet domicile-travail. La reconnaissance est examinée par la caisse.', sources: [mission] },
  { id: 10, theme: 'Accidents et maladies professionnelles', slides: '25, 28', text: 'Deux collègues sont blessés lors de leur covoiturage régulier entre leur domicile et le travail, sur l’itinéraire habituel. Quelle qualification envisager ?', choices: ['Un accident de mission dans tous les cas.', 'Un accident privé, car ils sont deux dans le véhicule.', 'Un accident de trajet.', 'Un accident sans lien possible avec le travail.'], correct: 2, explanation: 'Le déplacement domicile-travail relève du trajet protégé lorsque les conditions sont réunies. Le covoiturage régulier n’exclut pas cette reconnaissance.', sources: [accident] },
  { id: 11, theme: 'Accidents et maladies professionnelles', slides: '31–33', text: 'Une maladie doit-elle obligatoirement figurer dans un tableau pour pouvoir être reconnue d’origine professionnelle ?', choices: ['Non : une reconnaissance complémentaire est possible sous certaines conditions.', 'Oui : aucune reconnaissance n’est possible hors tableau.', 'Non : le salarié peut décider seul de la reconnaissance.', 'Oui, sauf si l’employeur signe une dérogation.'], correct: 0, explanation: 'Les tableaux permettent une présomption d’origine professionnelle si leurs conditions sont remplies. Une procédure complémentaire existe, avec l’intervention du CRRMP, sous des conditions spécifiques.', sources: [mp] },
  { id: 12, theme: 'Accidents et maladies professionnelles', slides: '20, 33–34', text: 'Pour un salarié du régime général, quel organisme notifie la décision de reconnaissance d’un accident du travail ou d’une maladie professionnelle ?', choices: ['Le CSE', 'L’URSSAF', 'L’employeur seul', 'La CPAM'], correct: 3, explanation: 'La CPAM instruit le dossier et notifie sa décision. Le salarié, l’employeur et les professionnels de santé contribuent au dossier sans se substituer à elle.', sources: [accident, mp] },
  { id: 13, theme: 'Le cadre de la prévention', slides: '42–43', text: 'À quoi correspond la jurisprudence ?', choices: ['Au règlement intérieur d’une entreprise.', 'Aux décisions des juridictions qui précisent l’application du droit.', 'À une liste de bonnes pratiques facultatives.', 'À toutes les consignes données par un responsable.'], correct: 1, explanation: 'La jurisprudence repose sur les décisions rendues par les juridictions. Elle éclaire l’interprétation des textes et leur application aux situations concrètes.', sources: [] },
  { id: 14, theme: 'Le cadre de la prévention', slides: '52–54', text: 'Quelle combinaison correspond à l’obligation générale de prévention de l’employeur ?', choices: ['Un affichage de consignes suffit.', 'La seule distribution d’équipements suffit.', 'Prévention, information et formation, organisation et moyens adaptés.', 'La délégation de toute la prévention aux élus du CSE.'], correct: 2, explanation: 'L’employeur doit combiner ces mesures et les adapter à l’évolution des circonstances. Une action isolée ne remplace pas une démarche cohérente.', sources: [obligation] },
  { id: 15, theme: 'Le cadre de la prévention', slides: '55', text: 'À quoi doit servir l’évaluation des risques ?', choices: ['À définir des actions de prévention, puis à suivre leur mise en œuvre.', 'À remplir un document sans modifier le travail.', 'À prouver qu’aucun accident ne pourra survenir.', 'À transférer la responsabilité de l’employeur au CSE.'], correct: 0, explanation: 'L’évaluation est un point de départ pour agir. Ses résultats sont transcrits dans le DUERP et doivent guider des mesures adaptées au travail réel.', sources: [{ label: 'INRS · Évaluation des risques professionnels', url: 'https://www.inrs.fr/demarche/evaluation-risques-professionnels/ce-qu-il-faut-retenir' }] },
  { id: 16, theme: 'Le cadre de la prévention', slides: '56', text: 'Parmi ces démarches, laquelle respecte les principes généraux de prévention ?', choices: ['Toujours commencer par les équipements de protection individuelle.', 'Choisir uniquement la solution la moins chère.', 'Accepter le risque si aucun accident n’a encore eu lieu.', 'Chercher à éviter le risque et privilégier la protection collective sur l’individuelle.'], correct: 3, explanation: 'Les principes de prévention donnent la priorité à l’évitement du risque et aux protections collectives. Les équipements individuels ne sont pas la première réponse par défaut.', sources: [principles] },
  { id: 17, theme: 'Le cadre de la prévention', slides: '60–62, 91–92', text: 'Un salarié est affecté à une tâche nouvelle présentant des risques. Que faut-il prévoir ?', choices: ['Le laisser apprendre seul, même sans consigne.', 'Une information et une formation à la sécurité adaptées à la tâche.', 'Attendre son premier incident pour évaluer ses besoins.', 'Lui demander seulement de signer un document.'], correct: 1, explanation: 'L’information doit être comprise et la formation adaptée aux risques de l’activité. Une signature ne prouve pas, à elle seule, la capacité à travailler en sécurité.', sources: [obligation] },
  { id: 18, theme: 'Responsabilités et rôle des élus', slides: '51, 70–73', text: 'Quel est l’objectif principal de la responsabilité civile ?', choices: ['Prononcer une peine d’emprisonnement.', 'Organiser les élections professionnelles.', 'Réparer un préjudice.', 'Fixer les horaires de travail.'], correct: 2, explanation: 'La responsabilité civile vise la réparation d’un dommage. La responsabilité pénale vise la sanction d’une infraction : ces deux logiques peuvent se combiner.', sources: [penal] },
  { id: 19, theme: 'Responsabilités et rôle des élus', slides: '51, 57, 64, 67', text: 'Faut-il nécessairement un accident avec blessure pour qu’une infraction aux règles de sécurité puisse être sanctionnée pénalement ?', choices: ['Non : certains manquements sont sanctionnables même sans dommage.', 'Oui : aucune sanction n’est possible sans blessure.', 'Oui : il faut au moins un mois d’arrêt.', 'Non : toute situation inconfortable constitue automatiquement une infraction.'], correct: 0, explanation: 'Une sanction peut viser le non-respect d’une règle assortie d’une sanction pénale, même sans blessure. Il faut toujours caractériser l’infraction ; elle n’est pas automatique.', sources: [penal] },
  { id: 20, theme: 'Responsabilités et rôle des élus', slides: '75–80', text: 'Un employeur empêche volontairement la tenue d’une réunion obligatoire du CSE. Quelle question juridique cela peut-il soulever ?', choices: ['Uniquement une question de politesse.', 'Une reconnaissance automatique de maladie professionnelle.', 'Une suppression automatique du CSE.', 'Un possible délit d’entrave au fonctionnement du CSE.'], correct: 3, explanation: 'Le fonctionnement régulier du CSE est protégé. Une entrave peut être constituée si les éléments de l’infraction sont réunis ; tout désaccord ne constitue pas une entrave.', sources: [obstruction] },
  { id: 21, theme: 'Responsabilités et rôle des élus', slides: '68–69', text: 'Le CSE signale un risque à l’employeur. Pourquoi garder une trace factuelle du signalement et des suites données ?', choices: ['Pour garantir automatiquement une condamnation.', 'Pour suivre la prévention et documenter les informations transmises.', 'Pour remplacer les mesures de protection par un compte rendu.', 'Pour dispenser l’employeur d’évaluer le risque.'], correct: 1, explanation: 'Une trace précise facilite le suivi des actions et documente la connaissance du risque. Elle ne permet pas, à elle seule, de conclure à une responsabilité pénale.', sources: [penal] },
  { id: 22, theme: 'Obligations des salariés et droit de retrait', slides: '74, 89–92', text: 'Quelle affirmation décrit correctement les obligations de sécurité du salarié ?', choices: ['Il est seul responsable de toute la prévention.', 'Il peut ignorer les consignes s’il possède de l’expérience.', 'Il prend soin de sa santé et de celle d’autrui selon sa formation, ses possibilités et les instructions reçues.', 'Ses obligations remplacent celles de l’employeur.'], correct: 2, explanation: 'Le salarié contribue à la sécurité dans ces conditions. Cette obligation ne remet pas en cause le principe de la responsabilité de l’employeur.', sources: [worker] },
  { id: 23, theme: 'Obligations des salariés et droit de retrait', slides: '94–96', text: 'Quel critère permet à un salarié d’exercer son droit de retrait ?', choices: ['Un motif raisonnable de penser que la situation présente un danger grave et imminent pour sa vie ou sa santé.', 'La seule existence d’un désaccord sur son planning.', 'Une preuve préalable et certaine qu’un accident va se produire.', 'Une autorisation écrite du CSE.'], correct: 0, explanation: 'Le critère est le motif raisonnable de penser qu’il existe un danger grave et imminent. L’appréciation dépend des circonstances ; une certitude préalable d’accident n’est pas exigée.', sources: [withdrawal] },
  { id: 24, theme: 'Obligations des salariés et droit de retrait', slides: '94, 97', text: 'Face à une situation justifiant un droit de retrait, quelle conduite correspond au Code du travail ?', choices: ['Attendre obligatoirement une autorisation écrite.', 'Quitter les lieux sans alerter personne.', 'Attendre la prochaine réunion du CSE.', 'Alerter immédiatement l’employeur et se retirer de la situation dangereuse.'], correct: 3, explanation: 'Le travailleur alerte immédiatement l’employeur et peut se retirer. L’exercice du droit n’est pas subordonné à une autorisation préalable de l’employeur.', sources: [withdrawal] },
  { id: 25, theme: 'Obligations des salariés et droit de retrait', slides: '98–99', text: 'Quelle limite doit être respectée lors de l’exercice du droit de retrait ?', choices: ['Il doit être exercé uniquement à plusieurs.', 'Il ne doit pas créer pour autrui une nouvelle situation de danger grave et imminent.', 'Il ne peut concerner que les salariés en CDI.', 'Il est interdit dès lors qu’il perturbe la production.'], correct: 1, explanation: 'Se retirer d’une situation dangereuse ne doit pas créer un nouveau danger grave et imminent pour d’autres personnes. Le droit peut être exercé individuellement ou collectivement.', sources: [others] },
];
