export const title = 'Les cinq enjeux de la prévention — UDAF 77';
export const disclaimer = 'Les situations proposées sont fictives et inspirées des activités de l’UDAF 77. Elles ne décrivent pas des événements avérés au sein de cette structure.';
export const definitions = [
  ['Humain', 'préserver la santé physique et mentale, l’intégrité et la qualité de vie des personnes.', 'Quelles conséquences pour la personne et sa santé ?'],
  ['Social', 'préserver la confiance, la coopération, les relations de travail et le dialogue social dans la structure.', 'Quelles conséquences pour le collectif de travail ?'],
  ['Économique', 'éviter les coûts et préserver le temps, les moyens et le fonctionnement de la structure.', 'Quels coûts ou quels moyens mobilisés ou économisés ?'],
  ['Juridique', 'respecter les obligations de prévention et prendre en compte les responsabilités.', 'Quelles obligations ou responsabilités sont en jeu ?'],
  ['Sociétal', 'prendre en compte les effets au-delà de la structure, notamment sur les familles, l’accès aux services et la collectivité.', 'Quelles conséquences pour les bénéficiaires et la société ?'],
] as const;
export const overlap = 'Cette grille sert de repère pédagogique. Les enjeux peuvent se recouper. Une activité d’accompagnement social ne relève pas automatiquement de l’enjeu social : ici, le social concerne le collectif de travail et le sociétal concerne les effets au-delà de la structure.';
export const instruction = 'Lisez la situation. Quel enjeu est principalement illustré par la conséquence décrite ? Repérez les mots qui justifient votre choix. D’autres enjeux peuvent aussi être concernés.';
export const situations = [
  { title: 'Après un entretien', text: 'Après un entretien au cours duquel elle a reçu des menaces, une salariée dort mal et appréhende de revenir à l’accueil.', answer: 0, explanation: 'Le récit insiste sur les conséquences pour la santé mentale et le bien-être de la salariée.', clue: '« dort mal et appréhende de revenir »', opening: 'Des conséquences sociales, économiques ou juridiques peuvent aussi apparaître, mais elles ne sont pas décrites ici.' },
  { title: 'Les dossiers à reprendre', text: 'À force de devoir reprendre les dossiers urgents des collègues absents, les membres d’une équipe se reprochent mutuellement de ne pas en faire assez.', answer: 1, explanation: 'La conséquence décrite est une dégradation des relations et de la coopération dans l’équipe.', clue: '« se reprochent mutuellement »', opening: 'La situation pourrait aussi avoir des effets sur la santé et sur le fonctionnement du service.' },
  { title: 'Un remplacement à organiser', text: 'Un arrêt prolongé oblige la structure à financer un remplacement et à consacrer du temps à la transmission des dossiers.', answer: 2, explanation: 'La carte met en avant l’argent et le temps supplémentaires nécessaires pour assurer la continuité du travail.', clue: '« financer un remplacement » et « consacrer du temps »', opening: 'L’enjeu humain de l’arrêt existe également, mais le texte ne précise pas ses conséquences pour la personne.' },
  { title: 'Les signalements de menaces', text: 'Après plusieurs signalements de menaces, la direction doit vérifier que ce risque a bien été évalué et que des mesures de prévention adaptées sont mises en œuvre.', answer: 3, explanation: 'Le texte met l’accent sur les obligations d’évaluation et de prévention des risques professionnels.', clue: '« doit vérifier que ce risque a bien été évalué »', opening: 'Le respect de ces obligations contribue notamment à protéger la santé des salariés. Ce scénario ne permet pas, à lui seul, de conclure à une faute.' },
  { title: 'Des démarches retardées', text: 'Dans ce scénario, la désorganisation liée à des absences prolonge les délais d’accompagnement. Certaines familles vulnérables peinent à obtenir l’aide nécessaire à leurs démarches.', answer: 4, explanation: 'Les conséquences dépassent le collectif de travail : elles concernent les personnes accompagnées et leur accès à l’aide.', clue: '« certaines familles […] peinent à obtenir l’aide nécessaire »', opening: 'La désorganisation peut aussi avoir un coût, mais ce sont ici les effets sur les bénéficiaires qui sont mis en avant.' },
  { title: 'Le travail sur écran', text: 'Un salarié qui travaille longtemps sur écran ressent des douleurs cervicales qui le gênent aussi dans ses activités personnelles.', answer: 0, explanation: 'La douleur et les répercussions sur la vie quotidienne de la personne constituent l’enjeu central.', clue: '« douleurs cervicales » et « activités personnelles »', opening: 'Des aménagements et une réflexion sur l’organisation du travail peuvent être discutés pendant le débriefing.' },
  { title: 'Des déplacements réorganisés', text: 'Pour limiter la fatigue, des déplacements professionnels sont mieux regroupés. La structure réduit aussi les dépenses de transport et le temps passé sur la route.', answer: 2, explanation: 'La diminution des dépenses et du temps de transport illustre le bénéfice économique de cette organisation.', clue: '« réduit […] les dépenses de transport et le temps »', opening: 'L’enjeu humain est également explicite, puisque la mesure vise à limiter la fatigue. Le reconnaître est pertinent : la situation illustre plusieurs enjeux.' },
  { title: 'Une confiance fragilisée', text: 'Des salariés estiment que leurs signalements de difficultés à l’accueil ne sont pas écoutés. Ils perdent confiance dans leur encadrement.', answer: 1, explanation: 'Le récit porte sur la confiance et la qualité du dialogue au sein de la structure.', clue: '« perdent confiance dans leur encadrement »', opening: 'Il faudrait davantage d’informations pour apprécier les mesures prises et les éventuelles questions juridiques.' },
  { title: 'Après un accident de déplacement', text: 'À la suite d’un accident lors d’un déplacement professionnel, la question du respect des obligations de prévention et de la responsabilité éventuelle de l’employeur est examinée.', answer: 3, explanation: 'La conséquence mise en avant concerne l’examen des obligations et des responsabilités. Un accident ne signifie pas automatiquement que l’employeur a commis une faute.', clue: '« respect des obligations » et « responsabilité éventuelle »', opening: 'Les conséquences humaines ou économiques peuvent également être importantes, mais elles ne sont pas détaillées.' },
  { title: 'Maintenir les permanences', text: 'Une organisation du travail qui préserve les salariés permet de maintenir des permanences accessibles à des personnes éloignées des services.', answer: 4, explanation: 'Le bénéfice mis en avant est l’accès à l’accompagnement et l’inclusion des personnes sur le territoire.', clue: '« permanences accessibles à des personnes éloignées des services »', opening: 'La protection des salariés constitue aussi un enjeu humain et contribue ici à un bénéfice sociétal.' },
];
export const scenario = 'Lors d’une permanence d’accompagnement budgétaire, un usager mécontent menace verbalement un salarié. Celui-ci se retrouve seul face à la situation. Les jours suivants, il appréhende les entretiens et finit par s’absenter. Ses rendez-vous sont répartis entre ses collègues.';
export const associationInstruction = 'Cet événement ne relève pas d’un seul enjeu. Associez chacune des conséquences suivantes à l’enjeu qu’elle illustre principalement.';
export const consequences = [
  { text: 'Le remplacement et la réorganisation mobilisent du temps et des moyens supplémentaires.', answer: 2, explanation: 'Il s’agit des ressources nécessaires pour faire face aux conséquences de l’événement.' },
  { text: 'Des personnes accompagnées subissent des reports de rendez-vous qui compliquent leurs démarches.', answer: 4, explanation: 'Les effets se répercutent sur les bénéficiaires et leur accès à l’accompagnement.' },
  { text: 'Le salarié ressent de l’anxiété et des troubles du sommeil.', answer: 0, explanation: 'La santé et le bien-être de la personne sont directement touchés.' },
  { text: 'La situation conduit à examiner l’évaluation du risque et les mesures de prévention prévues.', answer: 3, explanation: 'L’analyse porte sur la prise en compte des obligations de prévention, sans présumer d’une faute.' },
  { text: 'La répartition des rendez-vous provoque des tensions dans l’équipe.', answer: 1, explanation: 'Les relations et la coopération au sein du collectif se dégradent.' },
];
export const conclusion = 'Un même événement peut toucher les personnes, le collectif de travail, les moyens de la structure, ses responsabilités et les bénéficiaires. La prévention répond donc à plusieurs enjeux à la fois.';
export const questions = ['Quels enjeux avez-vous eu le plus de difficulté à distinguer ?', 'Comment la prévention peut-elle protéger à la fois les salariés et la qualité de l’accompagnement ?', 'Quel argument utiliseriez-vous pour expliquer l’intérêt de la prévention dans votre activité ?'];
export const resources = [
  ['UDAF 77 — Qui sommes-nous ?', 'https://www.udaf77.fr/qui-sommes-nous/'],
  ['UDAF 77 — Les services aux familles', 'https://www.udaf77.fr/les-services-aux-familles/'],
  ['UDAF 77 — Protection juridique des majeurs', 'https://www.udaf77.fr/les-services-aux-familles/protection-juridique-des-majeurs/'],
  ['INRS — Prévenir les agressions et violences externes', 'https://www.inrs.fr/risques/agressions-violences-externes/prevention'],
];
